[package]
name = "kiy_engine_v3"
version = "0.1.0"
edition = "2021"

[dependencies]
chess = "3.2.0"
candle-core = "0.9.2"
candle-nn = "0.9.2"
anyhow = "1.0.95"
safetensors = "0.7.0"
memmap2 = "0.9.5"
half = { version = "2.4.1", features = ["num-traits", "use-intrinsics", "rand_distr"] }
serde_json = "1.0"

[features]
noise = []
cuda = ["candle-core/cuda", "candle-nn/cuda"]
