[package]
name = "kiy_engine_v3"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.9.2"
candle-nn = "0.9.2"
anyhow = "1.0.100"
parking_lot = "0.12.5"
chess = "3.2.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
