[package]
name = "kiy_engine_v4_omega"
version = "0.4.1"
edition = "2021"

[dependencies]
chess = "3.2.0"
candle-core = "0.9.2"
candle-nn = "0.9.2"
anyhow = "1.0.95"
safetensors = "0.7.0"
memmap2 = "0.9.5"
dashmap = "6.1.0"

[features]
noise = []
cuda = ["candle-core/cuda", "candle-nn/cuda"]
